In [8]:
#import pandas library
import pandas as pd
#import numpy library
import numpy as np

In [2]:
#task 1
#create a DataFrame

In [9]:
#create project DataFrame
project_data = {
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
}

project_df = pd.DataFrame(project_data)

project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [4]:
# Create project DataFrame as CSV
project_df.to_csv("Project.csv",index=False)

In [10]:
import os
os.listdir()

['.ipynb_checkpoints',
 'capstone_project.ipynb',
 'Employee.csv',
 'Final.csv',
 'Project.csv',
 'seniority.csv']

In [11]:
#create Employee DataFrame
employee_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Name": ["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"],
    "Gender": ["M", "F", "M", "F", "F"],
    "City": ["Paris", "London", "Berlin", "Newyork", "Madrid"],
    "Age": [25, 27, 29, 31, 30]
}

employee_df = pd.DataFrame(employee_data)

employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [12]:
# Save Employee DataFrame as CSV
employee_df.to_csv("Employee.csv",index=False)

In [13]:
# Create Seniority Level DataFrame

seniority_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Designation Level": [2, 2, 3, 2, 3]
}

seniority_df = pd.DataFrame(seniority_data)

seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [14]:
#save Seniority DataFrame as CSV
seniority_df.to_csv("seniority.csv",index=False)

In [15]:
import os
os.listdir()

['.ipynb_checkpoints',
 'capstone_project.ipynb',
 'Employee.csv',
 'Final.csv',
 'Project.csv',
 'seniority.csv']

In [16]:
# Read all CSV files

project_df = pd.read_csv("Project.csv")
employee_df = pd.read_csv("Employee.csv")
seniority_df = pd.read_csv("seniority.csv")

In [17]:
#Task 2
# Read Project CSV file
project_df=pd.read_csv("Project.csv")
project_df

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  1.744333e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  1.744333e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [18]:
#Check missing values
project_df.isnull()

       ID  Project   Cost  Status
0   False    False  False   False
1   False    False  False   False
2   False    False  False   False
3   False    False  False   False
4   False    False  False   False
5   False    False  False   False
6   False    False  False   False
7   False    False  False   False
8   False    False  False   False
9   False    False  False   False
10  False    False  False   False
11  False    False  False   False
12  False    False  False   False
13  False    False  False   False

In [19]:
#count missing values
project_df.isnull().sum()

ID         0
Project    0
Cost       0
Status     0
dtype: int64

In [20]:
#calculate average cost
average_cost=project_df["Cost"].mean()
average_cost

1744333.3333333333

In [21]:
#Replace missing values using for loop
for i in range(len(project_df)):
    if pd.isna(project_df.loc[i,"Cost"]):
        project_df.loc[i,"Cost"]=average_cost

In [22]:
#Displayt upfated DataFrame
project_df

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  1.744333e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  1.744333e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [23]:
# Save updated Project DataFrame

project_df.to_csv("Project.csv", index=False)

In [24]:
# Read Employee CSV file
employee_df=pd.read_csv("Employee.csv")
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [25]:
#    Task 3
# Split Name into First Name and Last Name
employee_df[["First Name","Last Name"]]= employee_df["Name"].str.split(" ", expand=True)

In [26]:
# Remove old name column
employee_df.drop("Name",axis=1, inplace=True)

In [27]:
# Display updated Employee DataFrame
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [28]:
# save updated Employee DataFrame
employee_df.to_csv("Employee.csv", index=False)

In [29]:
# Read all CSV files

project_df = pd.read_csv("Project.csv")
employee_df = pd.read_csv("Employee.csv")
seniority_df = pd.read_csv("seniority.csv")

In [30]:
#    Task 4
# join all three DataFrame into one DataFrame. Name it Final
# Merge Project and Employee DataFrames

Final = pd.merge(project_df, employee_df, on="ID")

Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra
4,A005,Project 5,1.744333e+06,Finished,F,Madrid,30,Amy,Johny
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine
8,A001,Project 9,1.744333e+06,Ongoing,M,Paris,25,John,Alter
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny

In [31]:
# Merge with Seniority DataFrame

Final = pd.merge(Final, seniority_df, on="ID")

Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,1.744333e+06,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,1.744333e+06,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3

In [32]:
# Display information about Final DataFrame
Final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 14 non-null     object
 1   Project            14 non-null     object
 2   Cost               14 non-null     float64
 3   Status             14 non-null     object
 4   Gender             14 non-null     object
 5   City               14 non-null     object
 6   Age                14 non-null     int64
 7   First Name         14 non-null     object
 8   Last Name          14 non-null     object
 9   Designation Level  14 non-null     int64
dtypes: float64(1), int64(2), object(7)
memory usage: 1.2+ KB

In [33]:
#save final DataFrame
Final.to_csv("Final.csv",index=False)

In [35]:
#   task 5
# Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project
#cost only to employees who have finished the projects.
Final["Bonus"]=0
Final.loc[Final["Status"] == "Finished",
"Bonus"]=Final["Cost"]*0.05
Final

C:\Users\rajku\AppData\Local\Temp\ipykernel_14324\1476277870.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 50100.         225000.          87216.66666667  20000.
  15000.         150000.          10000.        ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Final.loc[Final["Status"] == "Finished",

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100.000000
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0.000000
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3,225000.000000
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.000000
4,A005,Project 5,1.744333e+06,Finished,F,Madrid,30,Amy,Johny,3,87216.666667
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2,0.000000
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000.000000
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3,0.000000
8,A001,Project 9,1.744333e+06,Ongoing,M,Paris,25,John,Alter,2,0.000000
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3,15000.000000
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2,0.000000
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.000000
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000.000000
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000.000000

In [36]:
#save updated Final DataFrame
Final.to_csv("final.csv",index=False)

In [38]:
#   task 6
#Demote employees whose project status is Failed
Final.loc[Final["Status"]=="Failed",
"Designation Level"] +=1
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100.000000
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0.000000
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3,225000.000000
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.000000
4,A005,Project 5,1.744333e+06,Finished,F,Madrid,30,Amy,Johny,3,87216.666667
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,3,0.000000
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000.000000
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,4,0.000000
8,A001,Project 9,1.744333e+06,Ongoing,M,Paris,25,John,Alter,2,0.000000
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3,15000.000000
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,3,0.000000
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.000000
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000.000000
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000.000000

In [43]:
# Remove employees whose Designation Level is greater than 4
Final=Final[Final["Designation Level"] <=4]
Final.shape

(1, 11)

In [42]:
# Save updated Final DataFrame
Final.to_csv("Final.csv",index=False)

In [45]:
Final=pd.read_csv("Final.csv")
Final.shape

(1, 11)

In [46]:
# Reload original CSV files
project_df = pd.read_csv("Project.csv")
employee_df = pd.read_csv("Employee.csv")
seniority_df = pd.read_csv("seniority.csv")

# Join them again
Final = pd.merge(project_df, employee_df, on="ID")
Final = pd.merge(Final, seniority_df, on="ID")

# Check shape
Final.shape

(14, 10)

In [47]:
# Task 6

# Decrease Designation Level by 1 where Status is Failed
Final.loc[Final["Status"] == "Failed", "Designation Level"] = Final.loc[
    Final["Status"] == "Failed", "Designation Level"
] - 1

# Display DataFrame
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,1.744333e+06,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,1
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,2
8,A001,Project 9,1.744333e+06,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,1
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3

In [48]:
# Save updated Final DataFrame
Final.to_csv("Final.csv", index=False)

In [49]:
# Task 7

# Add Mr. for Male employees
# Add Mrs. for Female employees
Final.loc[Final["Gender"] == "M", "First Name"] = "Mr. " + Final["First Name"]
Final.loc[Final["Gender"] == "F", "First Name"] = "Mrs. " + Final["First Name"]

# Remove Gender column
Final.drop("Gender", axis=1, inplace=True)
Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.002000e+06,Finished,Paris,25,Mr. John,Alter,2
1,A002,Project 2,2.000000e+06,Ongoing,London,27,Mrs. Alice,Luxumberg,2
2,A003,Project 3,4.500000e+06,Finished,Berlin,29,Mr. Tom,Sabestine,3
3,A004,Project 4,5.500000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,2
4,A005,Project 5,1.744333e+06,Finished,Madrid,30,Mrs. Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,London,27,Mrs. Alice,Luxumberg,1
6,A005,Project 7,4.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,Berlin,29,Mr. Tom,Sabestine,2
8,A001,Project 9,1.744333e+06,Ongoing,Paris,25,Mr. John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,Berlin,29,Mr. Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,Paris,25,Mr. John,Alter,1
11,A004,Project 12,1.000000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,Newyork,31,Mrs. Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,3

In [50]:
# Save updated Final DataFrame
Final.to_csv("Final.csv", index=False)

In [51]:
# Task 8
# Increase Designation Level by 1 if Age > 29
Final.loc[Final["Age"] > 29, "Designation Level"] = Final.loc[
    Final["Age"] > 29, "Designation Level"
] + 1

Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.002000e+06,Finished,Paris,25,Mr. John,Alter,2
1,A002,Project 2,2.000000e+06,Ongoing,London,27,Mrs. Alice,Luxumberg,2
2,A003,Project 3,4.500000e+06,Finished,Berlin,29,Mr. Tom,Sabestine,3
3,A004,Project 4,5.500000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,3
4,A005,Project 5,1.744333e+06,Finished,Madrid,30,Mrs. Amy,Johny,4
5,A002,Project 6,6.800000e+05,Failed,London,27,Mrs. Alice,Luxumberg,1
6,A005,Project 7,4.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,4
7,A003,Project 8,3.500000e+05,Failed,Berlin,29,Mr. Tom,Sabestine,2
8,A001,Project 9,1.744333e+06,Ongoing,Paris,25,Mr. John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,Berlin,29,Mr. Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,Paris,25,Mr. John,Alter,1
11,A004,Project 12,1.000000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,3
12,A004,Project 13,3.000000e+06,Finished,Newyork,31,Mrs. Nina,Adgra,3
13,A005,Project 14,2.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,4

In [52]:
# Save updated Final DataFrame
Final.to_csv("Final.csv", index=False)

In [53]:
# Task 9
# Group by ID and First Name, then calculate total project cost
TotalProjCost = Final.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

# Rename the Cost column
TotalProjCost.rename(columns={"Cost": "Total Cost"}, inplace=True)

# Display the result
TotalProjCost

     ID  First Name    Total Cost
0  A001    Mr. John  4.746333e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  2.344333e+06

In [54]:
# Save TotalProjCost DataFrame
TotalProjCost.to_csv("TotalProjCost.csv", index=False)

In [55]:
# Task 10
# Display employees whose city contains the letter 'o'
Final[Final["City"].str.contains("o", case=False)]

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3